name: daily-cron
on:
  schedule:
    - cron: "0 1,3,5,7,9,11,13,15,17,19,21,23 * * *"
  workflow_dispatch:
    
jobs:
  cron:
    runs-on: ubuntu-20.04
    outputs:
      output1: ${{ steps.nowdate.outputs.nowdate }}
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Tokyo"
      - uses: actions/checkout@master
      - name: set node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
      - name: make schedule
        run: |
          npm install
          npm run makeSchedule
      - name: Get date
        id: nowdate
        run: echo "set-output nowdate=$(date)" >> $GITHUB_OUTPUT
      - name: git push
        run: |
          git config --global user.email "dev01.topaz@gmail.com"
          git config --global user.name "yotsugi-vip"
          git add -A
          git commit -m "make schedule ${{steps.nowdate.outputs.nowdate}}"
          git push origin main
