name: daily-cron
on:
  schedule:
    - cron: "0 1,3,5,7,9,11,13,15,17,19,21,23 * * *"
  workflow_dispatch:
    
jobs:
  cron:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: set node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
      - name: make schedule
        run: |
          npm install
          npm run makeSchedule
      - name: Get date
        id: date
        run: echo "set-output name=date::$(date)"
      - name: git push
        run: |
          git add -A
          git commit -m "make schedule ${{steps.date.outputs.date}}"
          git push origin master
